name: YoungKingXCIII
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02973775425925851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#494949'
    - '#848484'
    - '#d2c4c1'
    - '#9c2b3f'
  brandStrength: 0.5
  lightness: 0.08911447017453611
  saturation: 0.727247794624418
  rhythmicContrast: 0.05148613499477506
purpose: []
