typography_spectrum: 0.75042
color:
  brandColors:
    - '#171717'
    - '#494949'
    - '#848484'
    - '#d2c4c1'
    - '#9c2b3f'
  brandStrength: 0.5
  lightness: 0.08911447017453611
  saturation: 0.727247794624418
  rhythmicContrast: 0.05148613499477506
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99076
analytics:
  google: null
  facebook: null
  twitter: null
name: Young King
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Young King
description: Music for Rebels
purpose: []
